apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: easypanel-data
  namespace: easy
  labels:
    app.kubernetes.io/name: easypanel
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  # storageClassName: standard  # 按集群 StorageClass 填写
