apiVersion: v1
kind: Service
metadata:
  name: easypanel
  namespace: easy
  labels:
    app.kubernetes.io/name: easypanel
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: easypanel
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
