apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: easy

resources:
  - frontend-configmap.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml

# 按需取消注释：
#  - ingress.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: easy
      app.kubernetes.io/name: easypanel
      app.kubernetes.io/component: frontend
    includeSelectors: false
