apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: easy

resources:
  - backend
  - frontend

images:
  - name: ghcr.io/ops-easy/easypanel-api
    newTag: latest
  - name: ghcr.io/ops-easy/easypanel-web
    newTag: latest
