apiVersion: v2
name: kube-bt-sync
description: K8s Ingress 与宝塔面板同步，内置 Web 控制台
type: application
version: 0.2.0
appVersion: "1.0.0"
keywords:
  - kubernetes
  - ingress
  - baota
maintainers:
  - name: kube-bt-sync
