export const criticalRoutes = [
  "/",
  "/setup",
  "/login",
  "/docs",
  "/cluster",
  "/cluster/compute",
  "/cluster/compute/pve",
  "/cluster/network",
  "/cluster/network/ikuai",
  "/cluster/ns/:namespace/pods/:podName",
  "/cluster/ns/:namespace/pods/:podName/terminal",
  "/cluster/vcenter/dashboard",
  "/cluster/vcenter/vms/:moref",
  "/cluster/apps",
  "/cluster/apps/redis",
  "/cluster/apps/kafka",
  "/cluster/apps/kafka/instance/:id",
  "/cluster/apps/openclaw",
  "/cluster/apps/openclaw/:id",
  "/cluster/apps/hermes",
  "/cluster/apps/dns",
  "/cluster/ai-inspect",
  "/account/settings",
  "/account/users",
  "/account/audit",
] as const;
